[package]
name = "iota-lib-rs"
edition = '2018'
version = "0.4.1"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["iota", "api"]
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://github.com/iotaledger/iota.rs"
documentation = "https://docs.rs/iota-lib-rs"
description = "A rust implementation of the IOTA Client API"

[lib]
name = "iota_lib_rs"

[workspace]
members = [
    "iota-pow",
    "iota-crypto",
    "iota-conversion",
    "iota-model",
    "iota-utils",
    "iota-constants",
    "iota-validation",
    "iota-signing",
    "iota-client"
]

[badges]
travis-ci = { repository = "njaremko/iota-lib-rs", branch = "master" }
appveyor = { repository = "njaremko/iota-lib-rs", branch = "master" }

[dependencies]
iota-crypto = { version = "0.3.0", path = "iota-crypto" }
iota-pow = { version = "0.2.1", path = "iota-pow" }
iota-conversion = { version = "0.3.0", path = "iota-conversion" }
iota-signing = { version = "0.2.1", path = "iota-signing" }
iota-model = { version = "0.3.0", path = "iota-model" }
iota-utils = { version = "0.2.1", path = "iota-utils" }
iota-validation = { version = "0.2.1", path = "iota-validation" }
iota-constants = { version = "0.2.1", path = "iota-constants" }
iota-client = { version = "0.3.0", path = "iota-client" }
crossbeam = "0.7"
chrono = "0.4"
crunchy = "0.2"
failure = "0.1"
lazy_static = "1.3"
num_cpus = "1.10"
rand = "0.6"
regex = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["run-for-all", "precommit-hook", "run-cargo-fmt"]