[package]
name = "iota-client"
version = "1.1.1"
authors = ["IOTA Stiftung"]
edition = "2021"
description = "The official, general-purpose IOTA client library in Rust for interaction with the IOTA network (Tangle)"
documentation = "https://wiki.iota.org/iota.rs/welcome"
homepage = "https://www.iota.org/"
repository = "https://github.com/iotaledger/iota.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "client"]
categories = ["cryptography::cryptocurrencies"]

[package.metadata.cargo-udeps.ignore]
normal = ["async-trait"]

[dependencies]
bee-rest-api = { version = "0.1.7", default-features = false }
bee-message = { version  = "0.1.6", default-features = false, features = ["serde"] }
bee-pow = { version = "0.2.0", default-features = false }
bee-common = { version = "0.5.0", default-features = false }
iota-crypto = { version = "0.9.1", default-features = false, features = ["std", "blake2b", "ed25519", "random", "slip10", "bip39", "bip39-en"] }

url = { version = "2.2.2", default-features = false }
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.68", default-features = false }
hex = { version = "0.4.3", default-features = false }
tokio = { version = "1.12.0", default-features = false, features = ["macros"], optional = true }
thiserror = { version = "1.0.29", default-features = false }
num_cpus = { version = "1.13.0", default-features = false }
log = { version = "0.4.14", default-features = false }
regex = { version = "1.5.4", default-features = false, features = ["std", "unicode-perl"] }
zeroize = { version = "1.4.1", default-features = false }

# sync
ureq = { version = "2.2.0", default-features = false, features = ["tls", "json"], optional = true }
# async
reqwest = { version = "0.11.6", default-features = false, features = ["json", "rustls-tls", "blocking"], optional = true }
futures = { version = "0.3.17", default-features = false, optional = true }

# MQTT
rumqttc = { version = "0.10.0", default-features = false, features = ["websocket"], optional = true }

# also used for storage
once_cell = { version = "1.8.0", default-features = false, features = ["std"], optional = true }

# storage
async-trait = {version = "0.1.51", default-features = false }
rusqlite = { version = "0.24.2", default-features = false, features = ["bundled"], optional = true }

# wasm
instant = { version = "0.1.12", default-features = false, optional = true }
gloo-timers = { git = "https://github.com/rustwasm/gloo", rev = "923e033688b18f03b63aa9c4823c26b4f7ae817c", default-features = false, features = ["futures"], optional = true }
# single thread pow for wasm
bee-ternary = { version = "0.5.2", default-features = false, optional = true }
bytes = { version = "1.1.0", default-features = false, optional = true }

[dev-dependencies]
dotenv = { version =  "0.15.0", default-features = false }
ureq = { version = "2.2.0", default-features = false, features = ["tls", "json"] }

[features]
default = ["async"]
sync = ["ureq", "tokio", "futures"]
async = ["reqwest", "futures", "tokio"]
mqtt = ["rumqttc", "once_cell", "futures"]
storage = ["rusqlite", "once_cell"]
wasm = ["reqwest", "futures", "gloo-timers", "instant", "bee-ternary", "bytes"]
#fallback to local PoW
pow-fallback = []

[[example]]
name = "10_mqtt"
required-features = ["mqtt"]

[[example]]
name = "storage"
required-features = ["storage"]
