[package]
name = "iota-client"
version = "1.1.1"
authors = [ "IOTA Stiftung" ]
edition = "2021"
description = "The official, general-purpose IOTA client library in Rust for interaction with the IOTA network (Tangle)"
documentation = "https://wiki.iota.org/iota.rs/welcome"
homepage = "https://www.iota.org/"
repository = "https://github.com/iotaledger/iota.rs"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "client" ]
categories = [ "cryptography::cryptocurrencies" ]

[package.metadata.cargo-udeps.ignore]
normal = [ "async-trait", "derive_builder", "slog-stdlog", "ureq" ]

[dependencies]
bee-rest-api = { git = "https://github.com/iotaledger/bee", rev = "12458320af158cef1ebc62b2b8c75f49184ae6dc", default-features = false }
bee-message = { git = "https://github.com/iotaledger/bee", rev = "12458320af158cef1ebc62b2b8c75f49184ae6dc", default-features = false, features = [ "serde", "dto" ] }
bee-pow = { git = "https://github.com/iotaledger/bee", rev = "12458320af158cef1ebc62b2b8c75f49184ae6dc", default-features = false }
fern-logger = { version = "0.5.0", default-features = false }
iota-crypto = { version = "0.10.0", default-features = false, features = [ "std", "chacha", "blake2b", "ed25519", "random", "slip10", "bip39", "bip39-en" ] }
packable = { version = "0.3.2", default-features = false, features = [ "serde", "primitive-types" ] }

async-trait = { version ="0.1.51", default-features = false }
derive_builder = { version = "0.11.1", default-features = false, features = [ "std" ]}
hex = { version = "0.4.3", default-features = false }
log = { version = "0.4.14", default-features = false }
num_cpus = { version = "1.13.0", default-features = false }
primitive-types = { version = "0.10.1", default-features = false }
regex = { version = "1.5.4", default-features = false, features = [ "std", "unicode-perl" ] }
serde = { version = "1.0.137", default-features = false, features = [ "derive" ] }
serde_json = { version = "1.0.68", default-features = false }
thiserror = { version = "1.0.29", default-features = false }
tokio = { version = "1.12.0", default-features = false, features = [ "macros", "rt-multi-thread", "time", "sync" ], optional = true }
url = { version = "2.2.2", default-features = false, features = [ "serde" ] }
zeroize = { version = "1.5.3", default-features = false }

# sync
ureq = { version = "2.2.0", default-features = false, features = [ "json" ], optional = true }
# async
reqwest = { version = "0.11.6", default-features = false, features = [ "json", "blocking" ], optional = true }
futures = { version = "0.3.17", default-features = false, features = [ "thread-pool" ], optional = true }

# MQTT
rumqttc = { version = "0.10.0", default-features = false, features = [ "websocket" ], optional = true }
once_cell = { version = "1.8.0", default-features = false, features = [ "std" ], optional = true }

# ledger hardware wallets
iota-ledger = { git = "https://github.com/iotaledger/ledger.rs", rev = "8c239b13b80e169aaa19cde9cd825e8444be0973", default-features = false, optional = true }

# stronghold secret manager integration
iota_stronghold = { version = "0.4.1", default-features = false, optional = true }
riker = { version = "0.4.2", default-features = false, optional = true }
# for stronghold
crypto05 = { package = "iota-crypto", version = "0.5.1", default-features = false, features = [ "slip10" ], optional = true }

# message_interface
backtrace = { version = "0.3.62", default-features = false, features = [ "std" ], optional = true }

# Temporary until it is updated by dependencies that require it
# https://github.com/slog-rs/stdlog/releases/tag/v4.1.1
slog-stdlog = { version = "4.1.1" }

[target.'cfg(target_family = "wasm")'.dependencies]
instant = { version = "0.1.12", default-features = false }
gloo-timers = { version = "0.2.3", default-features = false, features = [ "futures" ] }
# single thread pow for wasm
bee-ternary = { version = "0.5.2", default-features = false }

[dev-dependencies]
dotenv = { version = "0.15.0", default-features = false }

[features]
default = [ "async", "tls" ]
sync = [ "ureq", "tokio", "futures" ]
async = [ "reqwest", "futures", "tokio" ]
mqtt = [ "rumqttc", "once_cell", "futures" ]
ledger_nano = [ "iota-ledger" ]
tls = [ "reqwest/rustls-tls", "ureq/tls" ]
stronghold = [ "iota_stronghold", "riker", "crypto05" ]
message_interface = [ "backtrace" ]

# Node API core examples

[[example]]
name = "node_api_core_get_info"
path = "examples/node_api_core/02_get_info.rs"

[[example]]
name = "node_api_core_get_tips"
path = "examples/node_api_core/03_get_tips.rs"

[[example]]
name = "node_api_core_post_message"
path = "examples/node_api_core/04_post_message.rs"

[[example]]
name = "node_api_core_post_message_raw"
path = "examples/node_api_core/05_post_message_raw.rs"

#######

[[example]]
name = "10_mqtt"
required-features = [ "mqtt" ]

[[example]]
name = "ledger_nano"
required-features = [ "ledger_nano" ]

[[example]]
name = "stronghold"
required-features = [ "stronghold" ]

[[example]]
name = "0_address_generation"
path = "examples/offline_signing/0_address_generation.rs"

[[example]]
name = "1_transaction_preparation"
path = "examples/offline_signing/1_transaction_preparation.rs"

[[example]]
name = "2_transaction_signing"
path = "examples/offline_signing/2_transaction_signing.rs"

[[example]]
name = "3_send_message"
path = "examples/offline_signing/3_send_message.rs"

[[example]]
name = "all"
path = "examples/outputs/all.rs"

[[example]]
name = "all_automatic_input_selection"
path = "examples/outputs/all_automatic_input_selection.rs"

[[example]]
name = "alias"
path = "examples/outputs/alias.rs"

[[example]]
name = "basic"
path = "examples/outputs/basic.rs"

[[example]]
name = "foundry"
path = "examples/outputs/foundry.rs"

[[example]]
name = "native_tokens"
path = "examples/outputs/native_tokens.rs"

[[example]]
name = "nft"
path = "examples/outputs/nft.rs"
