[package]
name = "iota-lib-rs"
edition = '2018'
version = "0.1.3"
authors = ["Nathan Jaremko <nathan@jaremko.ca>"]
license = "MIT"
readme = "README.md"
keywords = ["iota", "api", "async"]
repository = "https://github.com/njaremko/iota-lib-rs"
homepage = "https://github.com/njaremko/iota-lib-rs"
documentation = "https://docs.rs/iota-lib-rs"
description = "A rust implementation of the IOTA API"
categories = ["asynchronous"]

[lib]
name = "iota_lib_rs"

[dependencies]
crossbeam = "0.5"
chrono = "0.4"
crunchy = "0.2"
failure = "0.1"
lazy_static = "1.2"
num_cpus = "1.8"
rand = "0.6"
regex = "1.0"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures-preview = "0.3.0-alpha.9"

[dev-dependencies]
criterion = "0.2"

[badges]
travis-ci = { repository = "njaremko/iota-lib-rs", branch = "master" }
appveyor = { repository = "njaremko/iota-lib-rs", branch = "master" }

[[bench]]
name = "kerl_benchmark"
harness = false

[[bench]]
name = "pow_benchmark"
harness = false
