[package]
name = "iota-client"
version = "1.1.0"
authors = ["IOTA Stiftung"]
edition = "2021"
description = "The official, general-purpose IOTA client library in Rust for interaction with the IOTA network (Tangle)"
documentation = "https://wiki.iota.org/iota.rs/welcome"
homepage = "https://www.iota.org/"
repository = "https://github.com/iotaledger/iota.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "client"]
categories = ["cryptography::cryptocurrencies"]

[package.metadata.cargo-udeps.ignore]
normal = ["async-trait"]

[dependencies]
bee-rest-api = { git = "https://github.com/iotaledger/bee", branch = "shimmer-develop", default-features = false }
bee-message = { git = "https://github.com/iotaledger/bee", branch = "shimmer-develop", default-features = false, features = ["serde1"] }
bee-pow = { git = "https://github.com/iotaledger/bee", branch = "shimmer-develop", default-features = false }
bee-common = { git = "https://github.com/iotaledger/bee", branch = "shimmer-develop", default-features = false }
bee-packable = { git = "https://github.com/iotaledger/bee", branch = "coordicide", default-features = false, features = [ "serde", "primitive-types" ] }
# bee-rest-api = { path = "../bee/bee-api/bee-rest-api",  default-features = false }
# bee-message = { path = "../bee/bee-message",  default-features = false, features = ["serde1"] }
# bee-pow = { path = "../bee/bee-pow",  default-features = false }
# bee-common = { path = "../bee/bee-common/bee-common",  default-features = false }
iota-crypto = { version = "0.9.1", default-features = false, features = ["std", "blake2b", "ed25519", "random", "slip10", "bip39", "bip39-en"] }

async-trait =  { version ="0.1.51", default-features = false }
url = { version = "2.2.2", default-features = false }
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.68", default-features = false }
hex = { version = "0.4.3", default-features = false }
tokio = { version = "1.12.0", default-features = false, features = ["macros"], optional = true }
thiserror = { version = "1.0.29", default-features = false }
num_cpus = { version = "1.13.0", default-features = false }
log = { version = "0.4.14", default-features = false }
regex = { version = "1.5.4", default-features = false, features = ["std", "unicode-perl"] }
zeroize = { version = "1.4.1", default-features = false }

# sync
ureq = { version = "2.2.0", default-features = false, features = ["tls", "json"], optional = true }
# async
reqwest = { version = "0.11.6", default-features = false, features = ["json", "rustls-tls", "blocking"], optional = true }
futures = { version = "0.3.17", default-features = false, optional = true }

# MQTT
rumqttc = { version = "0.10.0", default-features = false, features = ["websocket"], optional = true }
once_cell = { version = "1.8.0", default-features = false, features = ["std"], optional = true }

# ledger hardware wallets
iota-ledger = { git = "https://github.com/iotaledger/ledger.rs", rev = "8c239b13b80e169aaa19cde9cd825e8444be0973", default-features = false, optional = true }

# wasm
# to enable timeouts for browser and node.js
# patched version
wasm-timer = { git = "https://github.com/PhilippGackstatter/wasm-timer", rev = "448c2be0c4feeb6b5df1da265489232dff2f03c1", default-features = false, optional = true }
# wasm-timer = { version =  "0.2.5", default-features = false, optional = true }
# single thread pow for wasm
bee-crypto = { version = "0.3.0", default-features = false, optional = true }
bee-ternary = { version = "0.5.2", default-features = false, optional = true }
bytes = { version = "1.1.0", default-features = false, optional = true }

[dev-dependencies]
dotenv = { version =  "0.15.0", default-features = false }
ureq = { version = "2.2.0", default-features = false, features = ["tls", "json"] }

[features]
default = ["async", "ledger"]
sync = ["ureq", "tokio", "futures"]
async = ["reqwest", "futures", "tokio"]
mqtt = ["rumqttc", "once_cell", "futures"]
wasm = ["reqwest", "futures", "wasm-timer", "bee-crypto", "bee-ternary", "bytes"]
#fallback to local PoW
pow-fallback = []
ledger = ["iota-ledger"]

[[example]]
name = "10_mqtt"
required-features = ["mqtt"]

[[example]]
name = "ledger"
required-features = ["ledger"]

[[example]]
name = "0_address_generation"
path = "examples/offline_signing/0_address_generation.rs"

[[example]]
name = "1_transaction_preparation"
path = "examples/offline_signing/1_transaction_preparation.rs"

[[example]]
name = "2_transaction_signing"
path = "examples/offline_signing/2_transaction_signing.rs"

[[example]]
name = "3_send_message"
path = "examples/offline_signing/3_send_message.rs"