[package]
name = "examples"
version = "0.0.0"
authors = ["Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
publish = false

[dev-dependencies]
anyhow = "1.0.28"
iota-core = { path = "../iota-core" }
iota-bundle-miner = { path = "../iota-bundle-miner" }
smol = {version = "0.1.18", features = ["tokio02"] }
smol-potat = "0.3.1"
hex = "0.4.2"
tokio = { version = "1.0", features = ["full"] }

[[example]]
name = "generate_new_address"
path = "generate_new_address.rs"

[[example]]
name = "get_node_info"
path = "get_node_info.rs"

[[example]]
name = "get_unchecked_address"
path = "get_unchecked_address.rs"

[[example]]
name = "message_transfers"
path = "message_transfers.rs"

[[example]]
name = "send_transfers"
path = "send_transfers.rs"

[[example]]
name = "migration_address"
path = "migration_address.rs"

[[example]]
name = "generate_addresses"
path = "generate_addresses.rs"

[[example]]
name = "transfer_all"
path = "transfer_all.rs"

[[example]]
name = "migration"
path = "migration.rs"

[[example]]
name = "bundle_miner"
path = "bundle_miner.rs"

[[example]]
name = "permanode"
path = "permanode.rs"