[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2018"

[dev-dependencies]
tokio = { version = "0.2.22", features = ["full"] }
iota-core = { path = "../iota-core"}
hex = "0.4.2"
dotenv_codegen = "0.15.0"

[[example]]
name = "address"
path = "address.rs"

[[example]]
name = "balance"
path = "balance.rs"

[[example]]
name = "indexation"
path = "indexation.rs"

[[example]]
name = "transaction"
path = "transaction.rs"

[[example]]
name = "mqtt"
path = "mqtt.rs"

[[example]]
name = "multiple_outputs"
path = "multiple_outputs.rs"

[[example]]
name = "custom_inputs"
path = "custom_inputs.rs"

[[example]]
name = "search_address"
path = "search_address.rs"

[[example]]
name = "custom_parent"
path = "custom_parent.rs"