[package]
name = "examples"
version = "0.0.0"
authors = ["Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
publish = false

[dev-dependencies]
anyhow = "1.0.28"
iota-sdk = { path = "../iota-sdk" }
smol-potat = "0.1"
smol = { version = "0.1.2", features = ["tokio02"] }

[[example]]
name = "get-node-info"
path = "get-node-info.rs"

[[example]]
name = "send-transfers"
path = "send-transfers.rs"