[package]
name = "examples"
version = "0.0.0"
authors = ["Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
publish = false

[dev-dependencies]
anyhow = "1.0.28"
iota-core = { path = "../iota-core" }
iota-conversion = { version = "0.5.0", path = "../iota-conversion" }
smol = {version = "0.1.18", features = ["tokio02"] }
smol-potat = "0.3.1"

[[example]]
name = "generate_new_address"
path = "generate_new_address.rs"

[[example]]
name = "get_node_info"
path = "get_node_info.rs"

[[example]]
name = "get_unchecked_address"
path = "get_unchecked_address.rs"

[[example]]
name = "message_transfers"
path = "message_transfers.rs"

[[example]]
name = "send_transfers"
path = "send_transfers.rs"