name: Wasm publish to NPM

on: workflow_dispatch

jobs:
  publish-wasm:
    runs-on: ubuntu-latest
    env:
      working-directory: client/bindings/wasm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: 'wasm32-unknown-unknown'

      # Download a pre-compiled wasm-bindgen binary.
      - name: Install wasm-bindgen-cli
        uses: jetli/wasm-bindgen-action@24ba6f9fff570246106ac3f80f35185600c3f6c9
        with:
          version: '0.2.83'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm i -g yarn
        working-directory: ${{ env.working-directory }}

      - name: Install JS dependencies
        run: yarn
        working-directory: ${{ env.working-directory }}

      - name: Build project
        run: yarn build
        working-directory: ${{ env.working-directory }}

      - name: Publish WASM bindings to NPM
        shell: sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
        working-directory: ${{ env.working-directory }}